AntonioTurdo\Bundle\FileBundle\Entity\BaseFile:
    type: mappedSuperclass    
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        mimeType:
            column: mime_type
            type: string
            length: 255
            nullable: false
        size:
            column: size
            type: integer
            nullable: false
        hash:
            column: hash
            type: string
            length: 128
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        updatedAt:
            column: updated_at
            type: datetime
            nullable: false
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]   